---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  has_stack:
    description: 'Set it to true in case you already have stack installed.'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
