---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Kitten version.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
