---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Compile
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Security tests
        run: |
          yarn run security:auth ${{ secrets.SNYK_API_TOKEN }}
          yarn run security:test
      - name: Unit tests
        run: yarn run test
  functional_tests:
    name: Functional tests
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        has_stack: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Compile
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Setup Stack
        if: matrix.has_stack
        uses: mstksg/setup-stack@v2
      - name: Setup Kitten
        uses: fabasoad/setup-kitten-action@v1.0.0
        with:
          has_stack: ${{ matrix.has_stack }}
      - name: Run script (Linux, MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: kitten ./hello-world.ktn
      - name: Run script (Windows)
        if: matrix.os == 'windows-latest'
        run: kitten.exe ./hello-world.ktn
